import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer, Navbar } from "./components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans", // Establecer la variable CSS para la fuente
  weight: "100 900", // Rango de pesos para la fuente
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono", // Establecer la variable CSS para la fuente
  weight: "100 900", // Rango de pesos para la fuente
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* <head>
      </head> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar /> 
        <main>{children}</main> 
        <Footer /> 
      </body>
    </html>
  );
}
